from __future__ import annotations

import argparse
import json
import sys
from dataclasses import MISSING, fields
from pathlib import Path
from typing import Any, get_args, get_origin

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from custom_components.wuast_automation_bridge.const import EVENT_COMMAND, PLATFORMS  # noqa: E402
from custom_components.wuast_automation_bridge.models import EntityDefinition  # noqa: E402

DOC_PATH = ROOT / "docs" / "API.md"
SCHEMA_PATH = ROOT / "docs" / "entity-definition.schema.json"


def type_name(annotation: Any) -> str:
    if annotation is Any:
        return "any JSON value"
    origin = get_origin(annotation)
    if origin is list:
        return f"list[{type_name(get_args(annotation)[0])}]"
    if origin is dict:
        key, value = get_args(annotation)
        return f"object[{type_name(key)}, {type_name(value)}]"
    if origin is not None:
        return " | ".join(type_name(item) for item in get_args(annotation))
    return getattr(annotation, "__name__", str(annotation))


def json_schema() -> dict[str, Any]:
    properties: dict[str, Any] = {
        "unique_id": {"type": "string"},
        "platform": {"type": "string", "enum": list(PLATFORMS)},
        "name": {"type": "string"},
        "state": {},
        "attributes": {"type": "object"},
        "device_identifier": {"type": "string"},
        "device_name": {"type": "string"},
        "options": {"type": "array", "items": {"type": "string"}},
        "minimum": {"type": "number"},
        "maximum": {"type": "number"},
        "step": {"type": "number"},
        "command_timeout": {"type": "number", "exclusiveMinimum": 0},
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/wuast94/home-assistant-automation-bridge/entity-definition.schema.json",
        "title": "Wuast Automation Bridge entity definition",
        "type": "object",
        "additionalProperties": False,
        "required": ["unique_id", "platform", "name"],
        "properties": properties,
    }


def markdown(services: dict[str, Any]) -> str:
    lines = [
        "# API reference",
        "",
        "> Generated by `scripts/generate_docs.py`; do not edit manually.",
        "",
        "Transport is the authenticated Home Assistant WebSocket API. Runtime calls use",
        "the standard `call_service` WebSocket command.",
        "",
        "## Entity definition",
        "",
        "| Field | Type | Required | Default |",
        "|---|---|---:|---|",
    ]
    for item in fields(EntityDefinition):
        required = item.default is MISSING and item.default_factory is MISSING
        if required:
            default = "—"
        elif item.default is not MISSING:
            default = f"`{item.default!r}`"
        else:
            default = "empty collection"
        lines.append(f"| `{item.name}` | `{type_name(item.type)}` | {'yes' if required else 'no'} | {default} |")
    lines.extend([
        "", f"Platforms: {', '.join(f'`{item}`' for item in PLATFORMS)}.", "", "## Home Assistant actions", "",
    ])
    for service, definition in services.items():
        lines.extend([
            f"### `{service}` — {definition.get('name', service)}", "", definition.get("description", ""), "",
        ])
        service_fields = definition.get("fields", {})
        if service_fields:
            lines.extend(["| Field | Required | Selector |", "|---|---:|---|"])
            for name, field_definition in service_fields.items():
                selector = next(iter(field_definition.get("selector", {"object": None})))
                lines.append(f"| `{name}` | {'yes' if field_definition.get('required') else 'no'} | `{selector}` |")
            lines.append("")
        if service in {"create_entity", "update_entity"}:
            lines.extend([
                "```json",
                (
                    '{"definition":{"unique_id":"room-temperature","platform":"sensor",'
                    '"name":"Temperature","state":21.5}}'
                ),
                "```", "",
            ])
    lines.extend([
        "## Entity command event", "", f"Controllable entities emit `{EVENT_COMMAND}`.", "", "```json",
        '{"correlation_id":"…","unique_id":"runtime-switch","platform":"switch","command":"turn_on","value":null}',
        "```", "", "Return the result with `command_result` before `command_timeout` expires.", "",
        "## Machine-readable definition", "",
        "See [`entity-definition.schema.json`](entity-definition.schema.json).", "",
    ])
    return "\n".join(lines)


def write_or_check(*, check: bool) -> int:
    services = yaml.safe_load((ROOT / "custom_components" / "wuast_automation_bridge" / "services.yaml").read_text())
    outputs = {
        DOC_PATH: markdown(services),
        SCHEMA_PATH: json.dumps(json_schema(), indent=2, sort_keys=True) + "\n",
    }
    stale = [path for path, content in outputs.items() if not path.exists() or path.read_text() != content]
    if check:
        if stale:
            print("Generated documentation is stale: " + ", ".join(str(path.relative_to(ROOT)) for path in stale))
            return 1
        return 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    raise SystemExit(write_or_check(check=parser.parse_args().check))
